### ISSUE TITLE
Refuses to build

### ISSUE THREAD

**Issue by IndigoGuy** [adeyblue/GTVolTools#1]
ImageCoverter and ISOFileReplacer build without problems, but the rest complain about missing JSON namespaces, and properties being consumed before being set. Couldn't you have just provided a pre-built binary?

**Comment by adeyblue** [comment]
It's compiled in Net Framework 2.0 because I started doing it in VS2008 so it probably won't build directly out of the box with modern Visual Studios since they rewrote Winforms for newer .Net versions.

Nuget didn't exist in Net 2.0 days (20 years ago!) so the JSon.Net and SharpZipLib binaries were added to the repo, but on my machine they're symlinks, and I don't think Windows git likes Windows symlinks so it didn't add them properly.  It's fixed now and I just cloned the repo and tried it, everything builds fine (in VS2008)

And there have been prebuilt binaries (including those dependencies) on the releases page for a year and a half. The Releases link is mid-way down the right on the project 'code' page (the one with the code listing and readme at the bottom). This isn't that serious a project so I cba with tagging and branching and all that jazz making fancy new github releases for every single update, so I just continually update that one zip when I make changes, which is rarely.
